remote_theme: jekyll/minima
title: Bruno Vieira de Melo
description: 
author:
  name: Bruno Vieira de Melo
#  email: "brunobvieirademelo@gmail.com"
minima:
  skin: dark
  social_links:
    - title: Bruno at ORCID
      icon: orcid
      url: "https://bit.ly/2K0ODZ8"
    - title: Bruno at Google Scholar
      icon: google-scholar
      url: "https://scholar.google.com/citations?hl=en&user=2LjKg7YAAAAJ"
    - title: Bruno at Linkedin
      icon: linkedin
      ulr: "http://bit.ly/2uWfg7b"
    - title: Bruno at Instagram
      icon: instagram
      url: "https://bit.ly/4frWQSZ"
    - title: Bruno at X-Twitter
      icon: x-twitter
      url: "http://bit.ly/2TZOSTU"
    - title: Bruno at Facebook
      icon: facebook
      url: "http://bit.ly/2UzvKR0"
#    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?hl=en&user=2LjKg7YAAAAJ" }
#    - { platform: facebook,  user_url: "http://bit.ly/2UzvKR0" }
#    - { platform: twitter, user_url: "http://bit.ly/2TZOSTU" }
#    - { platform: linkedin, user_url: "http://bit.ly/2uWfg7b" }
  nav_pages:
    - index.md
    - indexpt.md
    - science.md
    - ciencia.md
    - publications.md
    - publicacoes.md
    - hobbies.md
    - passatempos.md
plugins:
  - jekyll-remote-theme

#header_pages:
#  - readme
